name: Unit Tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required packages

      - name: Run unit tests
        run: pytest tests/  # Run your tests located in the `tests/` folder